### ISSUE TITLE
ERROR: Call to undefined method CloudinaryLabs\CloudinaryLaravel\CloudinaryAdapter::getPathPrefix()

### ISSUE THREAD

**Issue by emran92** [cloudinary-devs/cloudinary-laravel#107]
Laravel Framework 7.30.6
PHP 7.4.33

ERROR: Call to undefined method CloudinaryLabs\CloudinaryLaravel\CloudinaryAdapter::getPathPrefix()

I'm getting this error when uploading file with livewire. 

I've changed the livewire config for temporary_file_upload.disk to 'cloudinary'.
File is uploading to cloudinary's livewire-tmp directory, I can see the file from the dashboard, but showing this error. 

Can you provide a fix please? 

<img width="400" alt="Screenshot 2023-11-10 at 11 26 06 PM" src="https://github.com/cloudinary-devs/cloudinary-laravel/assets/21041969/22be9115-f430-4d18-afe1-d671ee30dcf0">

Full Error log:

```
Error: Call to undefined method CloudinaryLabs\CloudinaryLaravel\CloudinaryAdapter::getPathPrefix() in file /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php on line 125

#0 /Users/emran/development/GitHub/project/vendor/livewire/livewire/src/TemporaryUploadedFile.php(30): Illuminate\Filesystem\FilesystemAdapter->path('livewire-tmp')
#1 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php(1227): Livewire\TemporaryUploadedFile->getPath()
#2 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php(1067): Illuminate\Validation\Validator->validateMimes('documentOne', Object(Livewire\TemporaryUploadedFile), Array)
#3 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(553): Illuminate\Validation\Validator->validateImage('documentOne', Object(Livewire\TemporaryUploadedFile), Array, Object(Illuminate\Validation\Validator))
#4 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(377): Illuminate\Validation\Validator->validateAttribute('documentOne', 'Image')
#5 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(408): Illuminate\Validation\Validator->passes()
#6 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(450): Illuminate\Validation\Validator->fails()
#7 /Users/emran/development/GitHub/project/vendor/livewire/livewire/src/ComponentConcerns/ValidatesInput.php(206): Illuminate\Validation\Validator->validate()
#8 /Users/emran/development/GitHub/project/app/Http/Livewire/User/UserVerify.php(70): Livewire\Component->validate(Array)
#9 /Users/emran/development/GitHub/project/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(95): App\Http\Livewire\User\UserVerify->updatedDocumentOne(Object(Livewire\TemporaryUploadedFile), NULL)
#10 /Users/emran/development/GitHub/project/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(54): Livewire\Component->callBeforeAndAfterSyncHooks('documentOne', Object(Livewire\TemporaryUploadedFile), Object(Closure))
#11 /Users/emran/development/GitHub/project/vendor/livewire/livewire/src/WithFileUploads.php(47): Livewire\Component->syncInput('documentOne', Object(Livewire\TemporaryUploadedFile))
#12 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Http\Livewire\User\UserVerify->finishUpload('documentOne', Array, false)
#13 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 /Users/emran/development/GitHub/project/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(149): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array)
#17 /Users/emran/development/GitHub/project/vendor/livewire/livewire/src/HydrationMiddleware/PerformActionCalls.php(38): Livewire\Component->callMethod('finishUpload', Array, Object(Closure))
#18 /Users/emran/development/GitHub/project/vendor/livewire/livewire/src/LifecycleManager.php(89): Livewire\HydrationMiddleware\PerformActionCalls::hydrate(Object(App\Http\Livewire\User\UserVerify), Object(Livewire\Request))
#19 /Users/emran/development/GitHub/project/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(13): Livewire\LifecycleManager->hydrate()
#20 /Users/emran/development/GitHub/project/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(21): Livewire\Connection\ConnectionHandler->handle(Array)
#21 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Livewire\Controllers\HttpConnectionHandler->__invoke('user.user-verif...')
#22 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Livewire\Controllers\HttpConnectionHandler), '__invoke')
#23 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route->runController()
#24 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route->run()
#25 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /Users/emran/development/GitHub/project/app/Http/Middleware/LastSeen.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\LastSeen->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\AuthenticateSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#38 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#46 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#47 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#48 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#49 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#50 /Users/emran/development/GitHub/project/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\DisableBrowserCache->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /Users/emran/development/GitHub/project/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#60 /Users/emran/development/GitHub/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#61 /Users/emran/development/GitHub/project/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#62 /Users/emran/development/GitHub/project/server.php(21): require_once('/Users/emran/de...')
#63 {main}
```

**Comment by joshmanders** [comment]
Hello @emran92 is this still an issue?

**Comment by joshmanders** [comment]
Closing. If this problem arrises again, please open a new issue.
